<a href="https://colab.research.google.com/github/Yuliana2001/Pila-Publica/blob/data_analysis/Analisis_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Libreias
import os
from google.colab import drive
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, HTML
from sklearn.preprocessing import LabelEncoder

In [ ]:
drive.mount('/content/drive')
folder_path = '/content/drive/MyDrive/Reto3'  # Cambia este path según tu carpeta
file_list = os.listdir(folder_path)
dataFrames={}
print("Archivos en la carpeta:")
for file in file_list:
    file_path = os.path.join(folder_path, file)
    if file.endswith('.csv'):
        # Intentar con múltiples codificaciones
        for encoding in ['utf-8', 'ISO-8859-1','latin-1']:
            try:
                pl = pd.read_csv(file_path, encoding=encoding, sep=';')
                print(f"✅ Archivo leído: {file}")
                break  # Sale del bucle si fue exitoso
            except UnicodeDecodeError:
              pass
        else:
            print(f"⚠️ No se pudo leer csv: {file}")
            continue  # Saltar este archivo si todas las codificaciones fallan
    else:
        try:
            pl = pd.read_excel(file_path)
            print(f"✅ Archivo leído: {file}")
        except Exception as e:
            print(f"⚠️ No se pudo leer el archivo Excel: {file}")
            continue
    # Guardar el DataFrame usando el nombre del archivo como clave
    dataFrames[file] = pl

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Archivos en la carpeta:
✅ Archivo leído: Transacciones.xlsx
✅ Archivo leído: Sesiones.csv
✅ Archivo leído: chart.csv
✅ Archivo leído: Otros errores.csv
✅ Archivo leído: Alertas.csv
✅ Archivo leído: Errores.csv
✅ Archivo leído: potencia-mxima-alcanzada.csv
✅ Archivo leído: Errores de conexion.csv

In [ ]:
# Recorremos el diccionario de DataFrames
for nombre_archivo, dataFrame in dataFrames.items():
    nulls = dataFrame.isnull().sum()
    non_nulls = dataFrame.notnull().sum()
    dtypes = dataFrame.dtypes

    # Columnas numéricas
    min_vals = dataFrame.min(numeric_only=True)
    max_vals = dataFrame.max(numeric_only=True)
    medians = dataFrame.median(numeric_only=True)

    resumen_nulos = pd.DataFrame({
        'Columna': dataFrame.columns,
        'Valores Nulos': nulls.values,
        'Valores No Nulos': non_nulls.values,
        'Mínimo': [min_vals.get(col, '') for col in dataFrame.columns],
        'Máximo': [max_vals.get(col, '') for col in dataFrame.columns],
        'Mediana': [medians.get(col, '') for col in dataFrame.columns],
        'Tipo de Dato': [dtypes[col] for col in dataFrame.columns]

    })

    # Mostrar nombre del archivo como título
    display(HTML(f"<h3 style='color: steelblue;'>📁 Archivo: {nombre_archivo}</h3>"))

    # Mostrar DataFrame estilizado
    display(
        resumen_nulos
        .style
        .set_caption("📊 Resumen de valores por columna")
        .set_table_attributes("style='display:inline'")
        .format(na_rep='-', precision=2)
    )

In [88]:
#Archivo Transacciones
#Separacion de las columnas de fecha-hora,
Transacciones=dataFrames['Transacciones.xlsx']
Transacciones['START SESSION'] = pd.to_datetime(Transacciones['START SESSION'], format='%d/%m/%Y %H:%M', errors='coerce')
Transacciones['SESSION END'] = pd.to_datetime(Transacciones['SESSION END'], format='%d/%m/%Y %H:%M', errors='coerce')
Transacciones['CHARGING END']=pd.to_datetime(Transacciones['CHARGING END'], format='%d/%m/%Y %H:%M', errors='coerce')
Transacciones['DATE_START SESSION'] = Transacciones['START SESSION'].dt.date
Transacciones['HOUR_START SESSION'] = Transacciones['START SESSION'].dt.time
Transacciones['DATE_CHARGING END'] = Transacciones['CHARGING END'].dt.date
Transacciones['HOUR_CHARGING END'] = Transacciones['CHARGING END'].dt.time
Transacciones['DATE_SESSION END'] = Transacciones['SESSION END'].dt.date
Transacciones['HOUR_SESSION END'] = Transacciones['SESSION END'].dt.time
#Eliminacion de columnas de fechas sin separar
Transacciones=Transacciones.drop(["SESSION END","CHARGING END","START SESSION"], axis=1)
#Eliminacion de columnas Nulas
Tansacciones=Transacciones.pop("AMOUNT")

In [94]:
Transacciones.rename(columns={
    'Capacidad Bateria (A)': 'BATTERY CAPACITY (A)',
    'Referencia': 'REFERENCE',
    'TIME CHARGING':'TIME CHARGING (min)',
    'TIME NO CHARGING':'TIME NO CHARGING (min)'
}, inplace=True)

In [95]:
#Buscando relacion entre las referencias y las caracteristicas
unicos_carga=len(Transacciones["BATTERY CAPACITY (A)"].unique())
unicos_referencia=len(Transacciones["REFERENCE"].unique())
unicos_energia=len(Transacciones["ENERGY (W)"].unique())
print(f"Valores unicos de Capacidad de carga: {unicos_carga}")
print(f"Valores unicos de REFERENCE: {unicos_referencia}")
#Relacion Entre la carga y la referencia
rel1 = Transacciones.groupby('BATTERY CAPACITY (A)')['REFERENCE'].nunique().max() == 1
rel2 = Transacciones.groupby('REFERENCE')['BATTERY CAPACITY (A)'].nunique().max() == 1

if rel1 and rel2:
    print("Existe una relación 1 a 1 entre BATTERY CAPACITY (A) y REFERENCE")
else:
    print("No existe una relación 1 a 1 entre BATTERY CAPACITY (A) y REFERENCE")

Valores unicos de Capacidad de carga: 8
Valores unicos de REFERENCE: 8
Existe una relación 1 a 1 entre BATTERY CAPACITY (A) y REFERENCE

In [96]:
Transacciones.head(10)

,ID,RFID,BATTERY CAPACITY (A),REFERENCE,SOCKET,ENERGY (W),TIME CHARGING (min),TIME NO CHARGING (min),DATE_START SESSION,HOUR_START SESSION,DATE_CHARGING END,HOUR_CHARGING END,DATE_SESSION END,HOUR_SESSION END
0,3744061,E2541124,18.00,C,2,8691,327,0,2024-07-03,07:09:00,2024-07-03,12:36:00,2024-07-03,12:37:00
1,3747743,4210747D,45.00,A,1,36194,343,30,2024-07-04,05:58:00,2024-07-04,11:42:00,2024-07-04,12:12:00
2,3766771,52FC1964,76.90,G,1,43690,445,195,2024-07-09,06:01:00,2024-07-09,13:27:00,2024-07-09,16:42:00
3,3794374,4210747D,45.00,A,2,55929,533,0,2024-07-16,05:59:00,2024-07-16,14:52:00,2024-07-16,14:52:00
4,3796049,E2541124,18.00,C,1,10488,256,0,2024-07-16,12:33:00,2024-07-16,16:50:00,2024-07-16,16:50:00
5,3823280,52FC1964,76.90,G,1,31306,320,0,2024-07-23,05:57:00,2024-07-23,11:17:00,2024-07-23,11:17:00
6,3824562,041E6A8A317780,60.48,B,1,31593,299,0,2024-07-23,11:23:00,2024-07-23,16:22:00,2024-07-23,16:22:00
7,3831236,4210747D,45.00,A,2,52202,497,98,2024-07-25,06:00:00,2024-07-25,14:18:00,2024-07-25,15:57:00
8,3852548,041E6A8A317780,60.48,B,2,35296,333,190,2024-07-30,06:35:00,2024-07-30,12:09:00,2024-07-30,15:20:00
9,3860203,4210747D,45.00,A,2,47151,449,143,2024-08-01,06:02:00,2024-08-01,13:32:00,2024-08-01,15:55:00

In [97]:
#Sesiones